// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoyGmTf0hMt12-O3YFB74obDqQb7YtX8',
    appId: '1:130385720776:web:671046822348e3ab267cfd',
    messagingSenderId: '130385720776',
    projectId: 'uyishi-67',
    authDomain: 'uyishi-67.firebaseapp.com',
    storageBucket: 'uyishi-67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ajRWuAwAT9fs0wClvye5dSPG5l3oprw',
    appId: '1:130385720776:android:cfc647ecdba8a0e2267cfd',
    messagingSenderId: '130385720776',
    projectId: 'uyishi-67',
    storageBucket: 'uyishi-67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0bgYZrQKlX2v5klCmVFOs1QgKODgYMmQ',
    appId: '1:130385720776:ios:1091bffe4d53760e267cfd',
    messagingSenderId: '130385720776',
    projectId: 'uyishi-67',
    storageBucket: 'uyishi-67.appspot.com',
    iosBundleId: 'com.example.uyishi65',
  );
}
